/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Sg721.types";
import * as _1 from "./Sg721.client";
import * as _2 from "./Sg721.react-query";
import * as _3 from "./Minter.types";
import * as _4 from "./Minter.client";
import * as _5 from "./Minter.react-query";
export namespace contracts {
  export const Sg721 = { ..._0,
    ..._1,
    ..._2
  };
  export const Minter = { ..._3,
    ..._4,
    ..._5
  };
}