import * as t from '@babel/types';
declare const BILLION: t.NumericLiteral;
export { BILLION };
export declare const recursiveNamespace: (names: any, moduleBlockBody: any) => any;
export declare const bindMethod: (name: string) => t.ExpressionStatement;
export declare const shorthandProperty: (prop: string) => t.ObjectProperty;
export declare const importStmt: (names: string[], path: string) => t.ImportDeclaration;
export declare const memberExpressionOrIdentifier: (names: any) => any;
export declare const memberExpressionOrIdentifierAminoCasing: (names: any, aminoCasingFn: Function) => any;
export declare const promiseTypeAnnotation: (name: any) => t.TSTypeAnnotation;
