import * as t from '@babel/types';
import { FromSDKJSONMethod } from './index';
export declare const fromSDKJSON: {
    string(args: FromSDKJSONMethod): t.ObjectProperty;
    number(args: FromSDKJSONMethod): t.ObjectProperty;
    double(args: FromSDKJSONMethod): t.ObjectProperty;
    float(args: FromSDKJSONMethod): t.ObjectProperty;
    int32(args: FromSDKJSONMethod): t.ObjectProperty;
    sint32(args: FromSDKJSONMethod): t.ObjectProperty;
    uint32(args: FromSDKJSONMethod): t.ObjectProperty;
    fixed32(args: FromSDKJSONMethod): t.ObjectProperty;
    sfixed32(args: FromSDKJSONMethod): t.ObjectProperty;
    bool(args: FromSDKJSONMethod): t.ObjectProperty;
    long(args: FromSDKJSONMethod): t.ObjectProperty;
    int64(args: FromSDKJSONMethod): t.ObjectProperty;
    uint64(args: FromSDKJSONMethod): t.ObjectProperty;
    sint64(args: FromSDKJSONMethod): t.ObjectProperty;
    fixed64(args: FromSDKJSONMethod): t.ObjectProperty;
    sfixed64(args: FromSDKJSONMethod): t.ObjectProperty;
    type(args: FromSDKJSONMethod): t.ObjectProperty;
    enum(args: FromSDKJSONMethod): t.ObjectProperty;
    bytes(args: FromSDKJSONMethod): t.ObjectProperty;
    duration(args: FromSDKJSONMethod): t.ObjectProperty;
    durationString(args: FromSDKJSONMethod): t.ObjectProperty;
    timestamp(args: FromSDKJSONMethod): t.ObjectProperty;
    timestampTimestamp(args: FromSDKJSONMethod): t.ObjectProperty;
    timestampDate(args: FromSDKJSONMethod): t.ObjectProperty;
    keyHash(args: FromSDKJSONMethod): t.ObjectProperty;
    array(args: FromSDKJSONMethod, expr: t.Expression): t.ObjectProperty;
};
export declare const arrayTypes: {
    string(): t.CallExpression;
    bool(): t.CallExpression;
    bytes(args: FromSDKJSONMethod): t.CallExpression;
    long(args: FromSDKJSONMethod): t.CallExpression;
    uint64(args: FromSDKJSONMethod): t.CallExpression;
    int64(args: FromSDKJSONMethod): t.CallExpression;
    sint64(args: FromSDKJSONMethod): t.CallExpression;
    fixed64(args: FromSDKJSONMethod): t.CallExpression;
    sfixed64(args: FromSDKJSONMethod): t.CallExpression;
    number(): t.CallExpression;
    uint32(): t.CallExpression;
    int32(): t.CallExpression;
    sint32(): t.CallExpression;
    fixed32(): t.CallExpression;
    sfixed32(): t.CallExpression;
    double(): t.CallExpression;
    float(): t.CallExpression;
    enum(args: FromSDKJSONMethod): t.CallExpression;
    type(args: FromSDKJSONMethod): t.CallExpression;
};
