import * as t from '@babel/types';

export const scopedImportObject = () => {
    return t.exportNamedDeclaration(
        t.variableDeclaration(
            'const',
            [
                t.variableDeclarator(
                    t.identifier('lcd'),
                    t.arrowFunctionExpression(
                        [
                            t.objectPattern([
                                t.objectProperty(
                                    t.identifier('restEndpoint'),
                                    t.identifier('restEndpoint'),
                                    false,
                                    true
                                )
                            ])
                        ],
                        t.objectExpression([
                            t.objectProperty(
                                t.identifier('cosmos'),
                                t.objectExpression([
                                    t.objectProperty(
                                        t.identifier('bank'),
                                        t.objectExpression([
                                            t.objectProperty(
                                                t.identifier('v1beta1'),
                                                t.newExpression(
                                                    t.memberExpression(
                                                        t.awaitExpression(
                                                            t.callExpression(
                                                                t.import(),
                                                                [
                                                                    t.stringLiteral(
                                                                        './proto/thing'
                                                                    )
                                                                ]
                                                            )
                                                        ),
                                                        t.identifier('LCDQueryClient'),
                                                        false
                                                    ),
                                                    [
                                                        t.objectExpression([
                                                            t.objectProperty(
                                                                t.identifier('restEndpoint'),
                                                                t.identifier('restEndpoint'),
                                                                false,
                                                                true
                                                            )
                                                        ])
                                                    ]
                                                )
                                            )
                                        ]),
                                        false,
                                        true
                                    )
                                ])
                            )
                        ]),
                        true
                    )
                )
            ]
        )
    )
}