/**
* This file and any referenced files were automatically generated by @cosmology/telescope@latest
* DO NOT MODIFY BY HAND. Instead, download the latest proto files for your chain
* and run the transpile command or yarn proto command to regenerate this bundle.
*/

import { BinaryReader, BinaryWriter } from "./binary";

/**
 * A type generated by Telescope 1.0.
 */
export interface TelescopeGeneratedType {
  readonly typeUrl: string;
  readonly encode: (
    message:
      | any
      | {
          [k: string]: any;
        },
    writer?: BinaryWriter
  ) => BinaryWriter;
  readonly decode: (input: BinaryReader | Uint8Array, length?: number) => any;
  readonly fromPartial: (object: any) => any;
}

export type GeneratedType = TelescopeGeneratedType;
